#PBS -N ENSEMBLE-TEST1
#PBS -S /bin/bash
#PBS -q M40
#PBS -j oe
#PBS -l nodes=5:ppn=1
#PBS -l walltime=00:05:00

# Load the ompi environment.  Use 'module avail' from the
# command line to see all available modules.

module load openmpi/1.5.5/gcc.4.7.2

# Display some basics about the job

echo
echo "================== nodes ===================="
cat $PBS_NODEFILE
echo
echo "================= job info  ================="
echo "Date:   $(date)"
echo "Job ID: $PBS_JOBID"
echo "Queue:  $PBS_QUEUE"
echo "Cores:  $PBS_NP"
echo "mpirun: $(which mpirun)"
echo
echo "=================== run ====================="

# Enter the PBS folder from which qsub is run

cd $PBS_O_WORKDIR

# Run imb with mpirun. Note that no -mca btl options should be
# used to ensure optimal performance.  Jobs will use Infiniband
# by default.

time mpirun mpirun /home/research/v5gavirangas/Documents/matlab_custom_clust/run_clust_p_mchine -m tmp/bootIdxTmpFile-gs7nCv -k tmp/bootIdxTmpFile-KfbE6F -i tmp/bootIdxTmpFile-BEyuRu -b 5 -r 20 -n 17 -c 24 -e tmp/bootIdxTmpFile-heHNqk -f tmp/bootIdxTmpFile-NfT6Z9  -g tmp/bootIdxTmpFile-Kp8pzZ -h tmp/bootIdxTmpFile-xurJ8O

retval=$?

# Display end date and return value

echo
echo "================== done ====================="
echo "Date:   $(date)"
echo "retval: $retval"
echo

# vim: syntax=sh
